server:
  port: 9001
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: was-metrics-service
monitor:
  # base URL for flow-controller API
  api-base-url: ${HOST_URL}
  user: ${HOST_USERNAME}
  password: ${HOST_PASSWORD}
  verify-ssl: false
  poll-interval-ms: 100
spring:
  jmx:
    enabled: true
  application:
    admin:
      enabled: true
  http:
    codecs:
      max-in-memory-size: 16MB